include("${CMAKE_CURRENT_LIST_DIR}/cryptoToolsFindBuildDir.cmake")

if(NOT EXISTS "${cryptoTools_BIN_DIR}/CMakeCache.txt")
    message(FATAL_ERROR "cache file does not exist at ${cryptoTools_BIN_DIR}")
endif()

LOAD_CACHE("${cryptoTools_BIN_DIR}/" READ_WITH_PREFIX LOAD_CACHE_CRYPTO_TOOLS_ 
    ENABLE_BOOST 
    ENABLE_RELIC
)
set(ENABLE_BOOST          ${LOAD_CACHE_CRYPTO_TOOLS_ENABLE_BOOST})
set(ENABLE_RELIC          ${LOAD_CACHE_CRYPTO_TOOLS_ENABLE_RELIC})
set(ENABLE_CIRCUITS       ${LOAD_CACHE_CRYPTO_TOOLS_ENABLE_CIRCUITS})
set(ENABLE_SIMPLESTOT_ASM ${LOAD_CACHE_CRYPTO_TOOLS_ENABLE_SIMPLESTOT_ASM})
set(ENABLE_MR_KYBER       ${LOAD_CACHE_CRYPTO_TOOLS_ENABLE_MR_KYBER})
